### ISSUE TITLE
Building wheels for collected packages: UNKNOWN

### ISSUE THREAD

**Issue by zhangjy-ge** [karlotness/adrt#1]
When installing adrt by using `CFLAGS="-O3 -fopenmp" python3.10 -m pip install .`, the name of software is UNKNOWN. Eventhough it is not an error, but I think it should be easily fixed.

![image](https://user-images.githubusercontent.com/100655819/217411098-9f7b930c-022f-4028-a170-927ec6ca4e41.png)

**Comment by karlotness** [comment]
Thanks for trying it out. I agree, that's odd and shouldn't be happening. Trying the same locally I don't see the same behavior, it seems to get the package name right.

To try to narrow down what's happening could we run through a few details?

1. Is the copy you're installing from a full git clone of the repository here, or did you download the `.tar.gz` file from PyPI, or download from some other source?

2. When you run `pip install .` are you in the root of the repository, at the same level as the `src/` directory and the `pyproject.toml` file?

3. What's the version of pip being used for the installation? It's possible that upgrading pip might help with this depending on the version.

4. If you have a copy of setuptools installed, what's the version of that? Probably `pip list` or `import setuptools; setuptools.__version__` can get it.

Thanks!

**Comment by zhangjy-ge** [comment]
I am using the latest code (just git pulled from the repository), and I am in the root directory when installing it (xxx/adrt/).
The pip version is `pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)`, and setup tools version is `setuptools             59.6.0`.

BTW, I have noticed that there is no "name" etc. in setup.py, would this cause the trouble? I have tried to add "name", "version" in setup.py and it will not have UNKNOWN issue now. But I am not an expert with setup.py so I could be wrong

**Comment by karlotness** [comment]
Thanks, that's helpful. I think the name not being in `setup.py` should be ok, it's supposed to find it in the `pyproject.toml` but somehow isn't.

I think I did manage to reproduce the same issue. Seems like it might be related to this [issue with setuptools](https://github.com/pypa/setuptools/issues/3269) and one [for pip](https://github.com/pypa/pip/pull/11466) and might be some quirk with how the system Python is set up on Ubuntu.

In testing (and based on comments in those issues) it does seem to work ok in a virtual environment. So if you run:
```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ CFLAGS="-O3 -fopenmp" pip install .
```
it should go through.

Unfortunately if that is the issue, I don't think there is much we can do about it. It looks like pip might have fixed it in a more recent version, but upgrading that for the system Python would be up to the Ubuntu packaging.

The install into the system environment should go through with the pre-built wheels on PyPI, though. So `pip install adrt` should work, and hopefully installing from source might be a bit less common and help most users avoid hiccups.

**Comment by zhangjy-ge** [comment]
I tried with venv and it did work here. If this is not a problem from adrt, then I think we are good!
